[project]
name = "dins"
version = "4.2.0"
description = "Dataset Information Service - Providing public metadata about files registered with the Internal File Registry"
dependencies = [
    "typer >= 0.19",
    "ghga-service-commons[api] >= 7.0",
    "ghga-event-schemas ~= 10.1",
    "hexkit[akafka,mongodb] >= 8.0",
]

[project.urls]
Repository = "https://github.com/ghga-de/dataset-information-service"

[project.scripts]
dins = "dins.__main__:run"
